# Generated by Django 3.1.7 on 2021-03-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='', max_length=8)),
                ('email', models.CharField(default='', max_length=40)),
                ('textTask', models.CharField(default='', max_length=250)),
                ('statusTask', models.IntegerField(default=0)),
            ],
        ),
    ]
