# Generated by Django 3.1.7 on 2021-03-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Task',
        ),
    ]
